export const CONST_URL_BASE = 'http://5ae97684531a58001414278c.mockapi.io/';
export const CONST_URL_AGENCIES = 'agencies';
export const CONST_URL_CATEGORIES = 'categories';
export const CONST_URL_PRICES = 'prices';

export const TYPE_AGENCIES_REQUEST = 'TYPE_AGENCIES_REQUEST';
export const TYPE_AGENCIES_SUCCESS = 'TYPE_AGENCIES_SUCCESS';
export const TYPE_CATEGORIES_REQUEST = 'TYPE_CATEGORIES_REQUEST';
export const TYPE_CATEGORIES_SUCCESS = 'TYPE_CATEGORIES_SUCCESS';
export const TYPE_PRICES_REQUEST = 'TYPE_PRICES_REQUEST';
export const TYPE_PRICES_SUCCESS = 'TYPE_PRICES_SUCCESS';
